<?php

include_once('menu_colors.features.inc');

/**
 * Implementation of hook_nodeapi().
 */
function menu_colors_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
	switch($op) {
		case 'view':
      $pages = array('fixed_width_landing_page', 'fluid_width_landing_page', 'fixed_width_secondary_page', 'fluid_width_secondary_page');
      if (in_array($node->type, $pages)) {
        drupal_add_js(drupal_get_path('module', 'menu_colors') . '/js/menu_colors.js'); 
        $color = $node->field_navbar_color[0]['value']; 
        if ($color) {
					drupal_add_css(drupal_get_path('module', 'menu_colors') . '/css/navbar/menu_colors_' . $color . '_nav.css');
					drupal_add_css(drupal_get_path('module', 'menu_colors') . '/css/common.css');
		  	}
        if (!$node->field_navbar_menu) {
          drupal_add_css(drupal_get_path('module', 'menu_colors') . '/css/navbar/menu_colors_navbar_hide.css');
        }
			}
      $pages = array('fixed_width_secondary_page', 'fluid_width_secondary_page', 'fixed_width_tertiary_page', 'fluid_width_tertiary_page');
			if (in_array($node->type, $pages)) {
        $color = $node->field_sidebar_color[0]['value'];
        if ($color) {
			    drupal_add_css(drupal_get_path('module', 'menu_colors') .'/css/sidebar/menu_colors_' . $color . '_side.css');
			    drupal_add_css(drupal_get_path('module', 'menu_colors') .'/css/common.css');
        }
        if ($node->field_hide_sidebar_left[0]['value'] == 'hide') {
          drupal_add_css(drupal_get_path('module', 'menu_colors') . '/css/sidebar/menu_colors_sidebar_left_hide.css');
        }
      }
		break;
  }
}

/**
 * Implementation of hook_preprocess().
 */
function menu_colors_preprocess(&$vars) {
  $pages = array('fixed_width_landing_page', 'fluid_width_landing_page', 'fixed_width_secondary_page', 'fluid_width_secondary_page', 'fixed_width_landing_page', 'fluid_width_landing_page', 'fixed_width_secondary_page', 'fluid_width_secondary_page');
  if (in_array($vars['node']->type, $pages)) {
    $vars['body_classes'] .= ' menu-colors';
  }
  if ($node->field_hide_sidebar_left[0]['value'] == 'hide') { 
    $vars['body_classes'] .= ' hide-sidebar-left';
  }
}

